### ISSUE TITLE
Failed to scan image using `docker scan`

### ISSUE THREAD

**Issue by rishabh1403** [docker/scan-cli-plugin#150] opened 2021-04-22 09:45 UTC
**Description**

**Steps to reproduce the issue:**
1. Created a new Image from a docker file
2.  run `docker scan IMAGE_NAME`

**Docker file used**
```
 # syntax=docker/dockerfile:1
 FROM node:12-alpine
 RUN apk add --no-cache python g++ make
 WORKDIR /app
 COPY . .
 # RUN yarn install --production
 CMD ["node", "src/index.js"]
```

**Build command used**
`docker build -t getting-started .`

**Scan command used**
` docker scan getting-started`

**Describe the results you received:**
I keep getting this error `Failed to scan image "IMAGE_NAME". Please make sure the image and/or repository exist, and that you are using the correct credentials.`

The scan works for all images except the ones I am building locally. I am also logged in to docker hub and snyk

**Describe the results you expected:**
The scan command should scan images correctly

**Additional information you deem important (e.g. issue happens only occasionally):**
The error only occurs for locally built images

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:01 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:13 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Output of `docker scan --version`:**

```
Version:    v0.7.0
Git commit: 0b3c564
Provider:   Snyk (1.461.0 (standalone))

```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.7.0)

Server:
 Containers: 5
  Running: 3
  Paused: 0
  Stopped: 2
 Images: 81
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-128-generic
 Operating System: Linux Mint 19
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.43GiB
 Name: stuart-thinkpad
 ID: CEDI:Z32B:7BIE:6LMO:XWXG:PXUG:CT54:JEX2:CNFF:IW5I:ATEL:NMKV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: rishabhloancrate
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running into the issue on my linux machine but not on my Mac

**Comment by glours** [comment] 2021-04-26 10:35
duplicate of #151 
fixed by #152 
Feel free to re-open this issue if the next version doesn't fix it.

**Closed by glours** 2021-04-26 10:35 UTC
